spring:
  application:
    name: transporte-viajes
  datasource:
    url: jdbc:mysql://localhost:3306/msrv_viajes
    username: micro_viajes
    password: transporte_viaje_msrv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0

management:
  tracing:
    sampling:
      probability: 1.0